// lib/leads-store.js
// Shared helper for reading/writing lead records using Netlify Blobs.
// Docs: https://docs.netlify.com/blobs/overview/

const { getStore } = require('@netlify/blobs');

function store() {
      return getStore('leads'); // creates/opens a "leads" blob store
}

/**
 * Lead record shape:
  * {
     *   id: string,              // e.g. place_id from Google Maps
      *   businessName: string,
       *   contactEmail: string,
        *   country: 'US' | 'KE',
         *   tag: 'no_website' | 'outdated_website',
          *   status: 'new' | 'contacted' | 'previewed' | 'paid' | 'built',
           *   previewHtml: string | null,   // generated by Groq builder
            *   amount: number | null,
             *   paymentRef: string | null,    // Stripe session id or Mpesa receipt
              *   createdAt: string,
               *   paidAt: string | null
                * }
                 */

                 async function getLead(id) {
                      const raw = await store().get(id, { type: 'json' });
                        return raw || null;
                 }

                 async function saveLead(lead) {
                      await store().setJSON(lead.id, lead);
                        return lead;
                 }

                 async function markPaid(id, { amount, paymentRef }) {
                      const lead = await getLead(id);
                        if (!lead) throw new Error(`Lead ${id} not found`);
                          lead.status = 'paid';
                            lead.amount = amount;
                              lead.paymentRef = paymentRef;
                                lead.paidAt = new Date().toISOString();
                                  await saveLead(lead);
                                    return lead;
                 }

                 module.exports = { getLead, saveLead, markPaid };
                 }
                 }
                 }
  }
}